### ISSUE TITLE
1.download_dockerfiles.py not working

### ISSUE THREAD

**Issue by x0rzkov** [vsoch/dockerfiles#10] opened 2020-01-02 08:00 UTC
Hi,

Hope you are all well !

The script 1.download_dockerfiles.py is not working as they change their css style.

Any ways to fix it ? Thanks in advance and thanks for your work

Cheers,
X

**Comment by vsoch** [comment] 2020-01-02 08:41
Yes this is known - unfortunately I haven’t figured out a way! If you find one please do share.

**Comment by x0rzkov** [comment] 2020-01-02 16:28
I tried with selenium but no luck
https://github.com/x0rzkov/dockerfiles-dinosaur

**Comment by vsoch** [comment] 2020-01-02 16:33
Haha yeah, I think I tried that too :) Thanks for trying!

**Comment by x0rzkov** [comment] 2020-01-02 17:58
there is always a way :-)
https://hub.docker.com/v2/repositories/aaronshaf/dynamodb-admin/dockerfile/

**Comment by vsoch** [comment] 2020-01-02 18:00
oh that's great! Would you like me to give a shot at updating the script?

**Comment by x0rzkov** [comment] 2020-01-02 18:06
yes would be nice !

**Comment by vsoch** [comment] 2020-01-02 18:12
okey doke, I'll give it a go! It will likely take me a few days, so let's assume sometime next week.

**Comment by x0rzkov** [comment] 2020-01-02 18:15
I will do it now

**Comment by vsoch** [comment] 2020-01-02 18:17
To be clear, I'm running it (started about 10 minutes ago now) and I was saying that it's likely to not finish imminently... please have patience.

**Comment by vsoch** [comment] 2020-01-02 18:17
If this method works, I'd want to update not just the script, but the entire database, and draft another release.

**Comment by x0rzkov** [comment] 2020-01-02 18:18
ok do your way :-)

**Comment by vsoch** [comment] 2020-01-02 22:19
hey @x0rzkov I'm running through this - for a large chunk of the repos that I can find, the Dockerfiles aren't actually provided there (you found a rare example of one that is provided). For example, look at the container here:

https://hub.docker.com/r/homeassistant/aarch64-homeassistant

For builds that aren't linked to a GitHub repo, there isn't much we can do - it was a non-reproducible push. But perhaps there is another programmatic way to derive a repo / source name, and look for a Dockerfile there? Or do you want to test extracting as many as we can find (likely a small set, but would be worth a try maybe?)

**Comment by vsoch** [comment] 2020-01-02 22:31
Another thing I started a while back was using the GitHub API to find Dockerfiles, but in that case we wouldn't know the name of the container. Maybe some combination of finding the repo in the context of the container's name would be logical, if it's possible?

**Comment by vsoch** [comment] 2020-01-02 23:30
Actually, it looks like a good number are producing results - let me let this run through completion and I'll give you an update for the count.

**Comment by x0rzkov** [comment] 2020-01-03 07:53
You can grab the following data from hub.docker.com api:
- https://hub.docker.com/v2/repositories/aaronshaf/dynamodb-admin/
- https://hub.docker.com/v2/users/aaronshaf/

For the source repository, I am still investigating...

**Comment by vsoch** [comment] 2020-01-05 17:28
hey @x0rzkov - I've updated the scripts, allowed them to run, and in total I have 96,767 Dockerfiles (fewer than before, 128K, but I still think this is okay). I've opened a PR [here](https://github.com/vsoch/dockerfiles/pull/11) for your review, and if all looks good we can merge and release another version of the database. If you have other ideas for discovering Dockerfiles let me know - if it's small / trivial it could be added to this release, but if it's more substantial it could be a 2.x release.

**Comment by x0rzkov** [comment] 2020-01-05 17:55
You can get repositories via
https://hub.docker.com/api/build/v1/source/?image=byrnedo%2Falpine-curl

objects.provider + objects.owner + objects.repository

```json
{
  "meta": {
    "limit": 25,
    "next": null,
    "offset": 0,
    "previous": null,
    "total_count": 1
  },
  "objects": [
    {
      "autotests": "OFF",
      "build_in_farm": true,
      "build_settings": [
        "/api/build/v1/setting/d113b893-7a71-4b58-9703-b050494fdead/",
        "/api/build/v1/setting/765f7c99-4de3-4a0c-b6ea-7655354502c6/",
        "/api/build/v1/setting/4cd8d616-328c-4b50-bb62-3f7cc1bff60b/"
      ],
      "channel": "Stable",
      "deploykey": "",
      "image": "byrnedo/alpine-curl",
      "owner": "byrnedo",
      "provider": "Github",
      "repo_links": true,
      "repository": "docker-alpine-curl",
      "resource_uri": "/api/build/v1/source/b3bd7a78-1cb4-45c0-9289-a12c559227c7/",
      "state": "Success",
      "uuid": "b3bd7a78-1cb4-45c0-9289-a12c559227c7"
    }
  ]
}
```

after, we can pick dockerfiles by fetching the git tree
https://developer.github.com/v3/git/trees/#get-a-tree-recursively

**Comment by vsoch** [comment] 2020-01-05 17:57
It's a good idea, but it doesn't help that greatly because the repositories are present for automated builds, and given automated builds the Dockerfiles are already available to us with the method that we just obtained.

**Comment by x0rzkov** [comment] 2020-01-05 18:53
Okay, I think that the search-terms.json is not enoughly using popular stack or framework keywords.

Also, the python script is quiet slow, so I started to rewrite it in golang https://github.com/x0rzkov/docker-search. I will use [badger kv](https://github.com/dgraph-io/badger) for the store.

```json
[
  "neo4j",
  "influxdb",
  "nsq",
  "ubuntu",
  "debian",
  "centos",
  "kibana",
  "vue",
  "quasar",
  "rust",
  "instagram",
  "elk",
  "stack",
  "skeleton",
  "cmake",
  "opencv",
  "keras",
  "numpy",
  "learn",
  "scikit-learn",
  "deep-learning",
  "dl",
  "similarity",
  "recognition",
  "recommander",
  "recommend",
  "tag",
  "tagger",
  "match",
  "matching",
  "cookiecutter",
  "make",
  "slim",
  "boilerplate",
  "kafka",
  "tensorflow",
  "alpine",
  "caffe",
  "ai",
  "ml",
  "brands",
  "google",
  "angular",
  "googlecloudplatform",
  "googlechrome",
  "golang",
  "gwtproject",
  "zxing",
  "v8",
  "twitter",
  "twbs",
  "twitter",
  "bower",
  "flightjs",
  "facebook",
  "facebookarchive",
  "boltsframework",
  "github",
  "atom",
  "microsoft",
  "dotnet",
  "aspnet",
  "exceptionless",
  "mono",
  "winjs",
  "node",
  "nodejs",
  "jquery",
  "jq",
  "grunt",
  "gruntjs",
  "angular",
  "angularjs",
  "ng",
  "ember",
  "emberjs",
  "meteor",
  "meteorjs",
  "gulp",
  "express",
  "expressjs",
  "d3",
  "polymer",
  "ionic",
  "seajs",
  "yeoman",
  "browserify",
  "requirejs",
  "underscore",
  "underscorejs",
  "modernizr",
  "phantom",
  "phantomjs",
  "metalsmith",
  "bootstrap",
  "django",
  "bottle",
  "bottlepy",
  "web2py",
  "webpy",
  "flask",
  "ipython",
  "fabric",
  "celery",
  "python",
  "ruby",
  "clojure",
  "lisp",
  "rust",
  "erlang",
  "golang",
  "go",
  "javascript",
  "js",
  "clojure",
  "coffeescript",
  "php",
  "perl",
  "swift",
  "css",
  "stylesheet",
  "ios",
  "osx",
  "unix",
  "android",
  "linux",
  "windows",
  "deprecated",
  "pdf",
  "polyfill",
  "framework",
  "dropbox",
  "webkit",
  "sql",
  "svg",
  "boilerplate",
  "seed",
  "rails",
  "rails3",
  "vim",
  "vi",
  "git",
  "github",
  "backbone",
  "docker",
  "emacs",
  "redis",
  "chrome",
  "sublime",
  "vagrant",
  "wordpress",
  "youtube",
  "apache",
  "jekyll",
  "puppet",
  "nginx",
  "sass",
  "scss",
  "markdown",
  "elasticsearch",
  "chef",
  "mongodb",
  "mongo",
  "cordova",
  "phonegap",
  "ansible",
  "openshift",
  "mysql",
  "couchbase",
  "firebase",
  "homebrew",
  "openstack",
  "maven",
  "hadoop",
  "spark",
  "jasmine",
  "hubot",
  "jruby",
  "couchdb",
  "travis",
  "bash",
  "coreos",
  "mustache",
  "zsh",
  "jenkins",
  "cassandra",
  "statsd",
  "eclipse",
  "knockout",
  "graphite",
  "textmate",
  "jed",
  "memcached",
  "mesos",
  "rabbitmq",
  "firefox",
  "ff",
  "postgres",
  "postgresql",
  "selenium",
  "gems",
  "rubygems",
  "zeromq",
  "zmq",
  "0mq",
  "tmux",
  "cyanogenmod",
  "tornado",
  "octopress",
  "dokku",
  "karma",
  "bitcoin",
  "handlebars",
  "qt",
  "minecraft",
  "unity",
  "unity3d",
  "cocos2d",
  "openssl",
  "amqp",
  "rabbitmq",
  "logstash",
  "sqlite",
  "v8",
  "fuse",
  "cocoa",
  "curl",
  "ffmpeg",
  "hhvm",
  "rake",
  "drupal",
  "gevent",
  "nagios",
  "chromium",
  "jenkinsci",
  "etcd",
  "kubernetes",
  "k8s",
  "react",
  "reactjs"
]
```

**Comment by vsoch** [comment] 2020-01-05 18:55
I'd be happy to add those search terms, but note that the implementation in Python is intentional - this is for _data scientists_ for which Python still reins much stronger than golang. That said, if you want to contribute scripts to go alongside the ones here, that works for me (I tend to also like GoLang).

**Comment by vsoch** [comment] 2020-01-05 18:56
What are you intentions with this data set, from a research perspective? Why do you want those terms added?

**Comment by x0rzkov** [comment] 2020-01-05 18:59
For myself, to find more easily dockerfile with specific sub-patterns, like if they are multi-staged or not, too identify specific packages.

After, if you want to make it more scientific related, we can re-use some piece of code from https://github.com/thoppe/arXiv2git, and check if they have a docker file.

**Comment by vsoch** [comment] 2020-01-05 19:01
Oh that's really cool! I'll start running the extended search terms later today to update the set. I'm currently using a fairly shoddy connection so it wouldn't work now. Shouldn't take too much longer after that. 

I'll take a look at the arxiv plugin after!

**Comment by x0rzkov** [comment] 2020-01-05 21:44
I think that my crawler will beat a record :-)

**Comment by vsoch** [comment] 2020-01-05 21:55
Congrats, have a cookie. 🍪 If you really want a fair comparison you’d need to add multiprocessing to the Python scripts.

**Comment by vsoch** [comment] 2020-01-05 22:14
The pull request is updated with about ~3k more containers. Please review there, thank you!

**Comment by x0rzkov** [comment] 2020-01-06 14:32
Hi,

Hope you are all well !

I refactored arxiv2git in order to make an universal tool for searching dockerfiles through the github api. It will look after all repositories having a pattern in their readme and it is working by year ranges. So you can define a scope of years for your search (now it is setup from 2007-2020, will update the code to use flag to setup these values).

**Ref:** https://github.com/x0rzkov/arXiv2git

**Examples to run:**
```bash
go run *.go --token=$GITHUB_TOKEN --query="arxiv in:description,readme fork:false"
go run *.go --token=$GITHUB_TOKEN --query="hub.docker.com in:description,readme fork:false"
```

For the moment, I hard coded to search patterns like "Dockerfile" or "docker-compose.yml" but it can be upgraded to some more flexible regexes or matching rules later.

About the other scrape, for the dinosaur dataset, it is still running as I set a concurrency of 4 parallel jobs only but sounds promising.

**Ref.** https://github.com/x0rzkov/docker-search

**To run it:**
```bash
go run queue.go
```

At https://github.com/x0rzkov/docker-search/blob/master/queue.go#L91, you can change the value for a higher number but be careful, there is a abuse detection system that will be triggered by docker if too much requests per second are requested.

I am tidying up the code for a more professional release.

Cheers,
X

**Comment by vsoch** [comment] 2020-01-06 14:45
Are you going to review the PR or not? It’s very confusing to come to my repo and request changes, I make them for you, and you ignore the request twice now and advertise your new tool... :/

**Comment by x0rzkov** [comment] 2020-01-06 15:05
Yeah, you can merge it. I am sorry for being confusing but just had the vision how to do it faster.
Sorry again, you can merge.

**Comment by vsoch** [comment] 2020-01-06 15:33
No worries! Glad my old graduate school weekend project was inspiring!

You know you could probably find database like https://www.gharchive.org/ that would be relatively simple to query to look for repos too.

**Comment by x0rzkov** [comment] 2020-01-06 15:45
I ll do a faceted search ui for making it over cool... Maybe, It can be a good project to add for the singularity org account ? A better docker container search engine... 

Already done one for twint, so it is easy to reproduce 
https://github.com/twintproject/twint-search#screenshots

**Comment by vsoch** [comment] 2020-01-06 15:47
It sounds like a cool project! Could you walk me through a few use cases for how it's relevant for Singularity? For example, when I'm looking for a Docker container, I usually search Docker Hub, and I'm tending to look for well known container bases (not random individuals with repos and containers that are not likely to be maintained.)

Since we resolved the issue here I'm going to close it, but if you want to open another issue on one of your repos and ping me I'd be glad to keep the discussion going, and see if I can help. Thanks again!

**Closed by vsoch** 2020-01-06 15:47 UTC
